name: Github

on:
  push:
    branches:
    - main
    - develop
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
    - main
    - develop
    paths-ignore:
      - '**.md'

jobs:
  server:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x
      - name: Check
        run: deno fmt ./src --check
      - name: Lint
        run: deno lint ./src
      - name: Test
        run: deno test ./src --allow-all
